Kongt.Web/Controllers/CommonController.cs
using Kongt.Common;
using Kongt.IServices;
using Kongt.Model;
using Kongt.ServiceProvider;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kongt.Web.Controllers
{

    [AllowAnonymous]
    public class CommonController : BaseController
    {
        // GET: Common
        public ActionResult _Left()
        {
            return View();
        }


        public ActionResult _Top()
        {
            return View();
        }



        #region 三级区域
        public ActionResult _LinkArea(string firstAreaId = "firstArea", string secondAreaId = "secondArea")
        {
            var list = ServiceFactory.Create<ICommonSetService>().GetFirstArea();
            ViewBag.firstAreaId = firstAreaId;
            ViewBag.secondAreaId = secondAreaId;
            return PartialView(list);
        }

        [HttpPost]
        public ActionResult _GetSecondArea(string firstArea)
        {
            var list = ServiceFactory.Create<ICommonSetService>().GetSecondAreaByFirstArea(firstArea);
            return Json(new JStat() { Obj = list });
        }
        #endregion


        #region 用水类别
        [ChildActionOnly]
        public ActionResult _WaterType(string id = "waterType", string name = "WaterTypeId", string cssClass = "select3")
        {
            ViewBag.id = id;
            ViewBag.name = name;
            ViewBag.cssClass = cssClass;
            var list = ServiceFactory.Create<ICommonSetService>().QueryWaterType(new QueryBase() { PageSize = 10000 });
            return PartialView(list.Rows);
        }
        #endregion



        /// <summary>
        /// 将枚举转化为列表
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>

        [ChildActionOnly]
        public ActionResult _EnumSelect(string className, string namespaces, string id = "customStat", string name = "customStat", string cssClass = "")
        {
            ViewBag.id = id;
            ViewBag.name = name;
            ViewBag.cssClass = cssClass;
            var customStatDic = EnumHelper.ToDictionary(string.Concat(namespaces, ".", className), namespaces);
            return PartialView(customStatDic);
        }



        [ChildActionOnly]
        public ActionResult _Employees(string id = "ReadPersonId", string name = "ReadPersonId", string cssClass = "select3")
        {
            ViewBag.id = id;
            ViewBag.name = name;
            ViewBag.cssClass = cssClass;
            var employeeModel = ServiceFactory.Create<ICommonSetService>().QueryEmployee(new QueryBase() { PageSize = 10000 });
            return PartialView(employeeModel.Rows);
        }



        [ChildActionOnly]
        public ActionResult _Managers(string id = "manager", string name = "manager", string cssClass = "select3")
        {
            ViewBag.id = id;
            ViewBag.name = name;
            ViewBag.cssClass = cssClass;
            var pmodel = ServiceFactory.Create<IManagerService>().Query(new QueryBase() { PageIndex = 1, PageSize = 10000 });
            return PartialView(pmodel.Rows);
        }

    }
}

Kongt.Web/Controllers/CommonSetController.cs

using Kongt.IServices;
using Kongt.Model;
using Kongt.ServiceProvider;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;

namespace Kongt.Web.Controllers
{

    /// <summary>
    /// 基本设置
    /// </summary>
    public class CommonSetController : BaseUserController
    {
        ICommonSetService commonservice = ServiceFactory.Create<ICommonSetService>();



        /// <summary>
        /// 居住区域设置
        /// </summary>
        public ActionResult AreaSet(QueryBase p)
        {
            var pModel = commonservice.QueryArea(p);
            PagedList<Area> model = new PagedList<Area>(pModel.Rows, p.PageIndex, p.PageSize, pModel.Count);
            return View(model);
        }


        /// <summary>
        /// 增加修改
        /// </summary>
        /// <param name="area"></param>
        [HttpPost]
        public JsonResult AreaEdit(Area area)
        {
            if (ModelState.IsValid)
            {
                if (area.Id > 0)
                {
                    commonservice.UpdateArea(area);
                }
                else
                {
                    commonservice.CreateArea(area);
                }
                return Json(new JStat());
            }
            else
            {
                return Json(new JStat() { Succeed = false, Msg = ModelState.Values.First().Errors[0].ErrorMessage });
            }
        }


        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="area"></param>   
        [HttpPost]
        public JsonResult AreaDel(long areaId)
        {
            commonservice.DeleteArea(areaId);
            return Json(new JStat());
        }



        /// <summary>
        /// 用水类别设置
        /// </summary>
        public ActionResult WaterTypeSet(QueryBase p)
        {
            var pModel = commonservice.QueryWaterType(p);
            PagedList<WaterType> model = new PagedList<WaterType>(pModel.Rows, p.PageIndex, p.PageSize, pModel.Count);
            return View(model);
        }


        /// <summary>
        /// 增加修改
        /// </summary>
        /// <param name="area"></param>
        [HttpPost]
        public JsonResult WaterTypeEdit(WaterType type)
        {
            if (ModelState.IsValid)
            {
                if (type.Id > 0)
                {
                    commonservice.UpdateWaterType(type);
                }
                else
                {
                    commonservice.CreateWaterType(type);
                }
                return Json(new JStat());
            }
            else
            {
                return Json(new JStat() { Succeed = false, Msg = ModelState.Values.First().Errors[0].ErrorMessage });
            }
        }


        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="area"></param>
        [HttpPost]
        public JsonResult WaterTypeDel(long typeId)
        {
            commonservice.DeleteWaterType(typeId);
            return Json(new JStat());
        }


        /// <summary>
        /// 抄表人员设置
        /// </summary>
        public ActionResult ReadMeterset(QueryBase p)
        {
            var pModel = commonservice.QueryEmployee(p);
            PagedList<EmployeeInfo> model = new PagedList<EmployeeInfo>(pModel.Rows, p.PageIndex, p.PageSize, pModel.Count);
            return View(model);
        }



        /// <summary>
        /// 增加修改
        /// </summary>
        /// <param name="area"></param>
        [HttpPost]
        public JsonResult ReadMeterEdit(EmployeeInfo employee)
        {
            if (ModelState.IsValid)
            {
                if (employee.Id > 0)
                {
                    commonservice.UpdateEmployee(employee);
                }
                else
                {
                    commonservice.CreateEmployee(employee);
                }
                return Json(new JStat());
            }
            else
            {

                return Json(new JStat() { Succeed = false, Msg = ModelState.Values.First().Errors[0].ErrorMessage });
            }
        }


        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="area"></param>
        [HttpPost]
        public JsonResult ReadMeterDel(long id)
        {
            commonservice.DeleteEmployee(id);
            return Json(new JStat());
        }



        /// <summary>
        /// 附加费设置
        /// </summary>
        public ActionResult ExtendChargeSet(QueryBase p)
        {
            var pModel = commonservice.QueryExtendCharge(p);
            PagedList<ExtendCharge> model = new PagedList<ExtendCharge>(pModel.Rows, p.PageIndex, p.PageSize, pModel.Count);
            return View(model);
        }

        /// <summary>
        /// 增加修改
        /// </summary>
        /// <param name="area"></param>
        [HttpPost]
        public JsonResult ExtendChargeEdit(ExtendCharge charge)
        {
            if (ModelState.IsValid)
            {
                if (charge.Id > 0)
                {
                    commonservice.UpdateExtendCharge(charge);
                }
                else
                {
                    commonservice.CreateExtendCharge(charge);
                }
                return Json(new JStat());
            }
            else
            {
                return Json(new JStat() { Succeed = false, Msg = ModelState.Values.First().Errors[0].ErrorMessage });
            }
        }


        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="area"></param>   
        [HttpPost]
        public JsonResult ExtendChargeDel(long id)
        {
            commonservice.DeleteExtendCharge(id);
            return Json(new JStat());
        }







        /// <summary>
        /// 材料名称设置
        /// </summary>
        public ActionResult DocumentNameSet(QueryBase p)
        {
            var pModel = commonservice.QueryDocument(p);
            PagedList<Document> model = new PagedList<Document>(pModel.Rows, p.PageIndex, p.PageSize, pModel.Count);
            return View(model);
        }

        /// <summary>
        /// 增加修改
        /// </summary>
        /// <param name="area"></param>
        [HttpPost]
        public JsonResult DocumentNameEdit(Document doc)
        {
            if (ModelState.IsValid)
            {
                if (doc.Id > 0)
                {
                    commonservice.UpdateDocument(doc);
                }
                else
                {
                    commonservice.CreateDocument(doc);
                }
                return Json(new JStat());
            }
            else
            {
                return Json(new JStat() { Succeed = false, Msg = ModelState.Values.First().Errors[0].ErrorMessage });
            }
        }


        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="area"></param>   
        [HttpPost]
        public JsonResult DocumentNameDel(long id)
        {
            commonservice.DeleteDocument(id);
            return Json(new JStat());
        }






        /// <summary>
        /// 滞纳金设置
        /// </summary>
        public ActionResult LateFeeSet(QueryBase p)
        {
            var pModel = commonservice.QueryLateFee(p);
            PagedList<LateFee> model = new PagedList<LateFee>(pModel.Rows, p.PageIndex, p.PageSize, pModel.Count);
            return View(model);
        }

        /// <summary>
        /// 增加修改
        /// </summary>
        /// <param name="area"></param>
        [HttpPost]
        public JsonResult LateFeeEdit(LateFee fee)
        {
            if (ModelState.IsValid)
            {
                if (fee.Id > 0)
                {
                    commonservice.UpdateLateFee(fee);
                }
                else
                {
                    commonservice.CreateLateFee(fee);
                }
                return Json(new JStat());
            }
            else
            {
                return Json(new JStat() { Succeed = false, Msg = ModelState.Values.First().Errors[0].ErrorMessage });
            }
        }


        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="area"></param>   
        [HttpPost]
        public JsonResult LateFeeDel(long id)
        {
            commonservice.DeleteLateFee(id);
            return Json(new JStat());
        }

        /// <summary>
        /// 阶梯水价设置
        /// </summary>
        public ActionResult LadderFeeSet(QueryBase p)
        {
            var pModel = commonservice.QueryLadderFee(p);
            PagedList<LadderFee> model = new PagedList<LadderFee>(pModel.Rows, p.PageIndex, p.PageSize, pModel.Count);
            return View(model);
        }


        /// <summary>
        /// 增加修改
        /// </summary>
        /// <param name="area"></param>
        [HttpPost]
        public JsonResult LadderFeeEdit(LadderFee fee)
        {
            if (ModelState.IsValid)
            {
                if (fee.Id > 0)
                {
                    commonservice.UpdateLadderFee(fee);
                }
                else
                {
                    commonservice.CreateLadderFee(fee);
                }
                return Json(new JStat());
            }
            else
            {
                return Json(new JStat() { Succeed = false, Msg = ModelState.Values.First().Errors[0].ErrorMessage });
            }
        }


        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="area"></param>   
        [HttpPost]

Kongt.Web/Views/CommonSet/ladderfeeset.cshtml
@model PagedList<LadderFee>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>无标题文档</title>
    <link href="/css/style.css" rel="stylesheet" type="text/css" />
    <link href="/css/select.css" rel="stylesheet" type="text/css" />
    <link href="/css/ladderinfostyle.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="/js/jquery.js"></script><script src="/js/jquery.form.js"></script>
    <script type="text/javascript" src="/js/jquery.idTabs.min.js"></script>
    <script type="text/javascript" src="/js/select-ui.min.js"></script> 
    <script language="javascript">
$(function(){
	//导航切换
	$(".imglist li").click(function(){
		$(".imglist li.selected").removeClass("selected")
		$(this).addClass("selected");
	})
})
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            var api = {
                edit: "/commonset/LadderfeeEdit",
                del: "/commonset/LadderfeeDel"
            }
            $('#form1').attr('action', api.edit);
            $('#form2').attr('action', api.edit);

            //抄表添加
            $(".clickreaderfromadd").click(function () {
                $(".tipreaderfromadd").fadeIn(200);
            });

            $(".tiptopreaderfromadd a").click(function () {
                $(".tipreaderfromadd").fadeOut(200);
            });

            $(".surereaderfromadd").click(function () {
                $('#form1').ajaxSubmit({
                    success: function (data) {
                        if (data.Succeed) {
                            window.location.reload();
                        } else {
                            alert(data.Msg);
                        }
                    }
                })



            });

            $(".cancelreaderfromadd").click(function () {
                $(".tipreaderfromadd").fadeOut(100);
            });


            //抄表修改
            $(".clickfromchangemodify").click(function () {
                var count = $("input:checked").length;
                if (count < 1) {
                    alert("至少选择一项进行修改！");
                }
                else if (count > 1) {
                    alert("只能选择一项进行修改！");
                }
                else {
                    $(".tipfromchangemodify").fadeIn(200);
                    $obj = $("input:checked").parents("tr");
                    $('#form2').find("input[name='Id']").val($obj.attr("Id"));

                    if ($obj.attr("WaterTypeId")) {
                        $('#form2').find("select[name='WaterTypeId']").find("option[value='" + $obj.attr("WaterTypeId") + "']").attr("selected", true);
                        $('#form2').find("select[name='WaterTypeId']").prev().find("em:first").text($('#form2').find("select[name='WaterTypeId']").find("option:selected").text());
                    }
                     
                    $('#form2').find("input[name='START']").val($obj.attr("START"));
                    $('#form2').find("input[name='EndTo']").val($obj.attr("EndTo"));
                    $('#form2').find("input[name='Price']").val($obj.attr("Price"));
                    $('#form2').find("input[name='DESCRIPTION']").val($obj.attr("DESCRIPTION"));  
                }
            });

            $(".tiptopfromchangemodify a").click(function () {
                $(".tipfromchangemodify").fadeOut(200);
            });

            $(".surefromchangemodify").click(function () {

                $('#form2').ajaxSubmit({
                    success: function (data) {
                        if (data.Succeed) {
                            window.location.reload();
                        } else {
                            alert(data.Msg);
                        }
                    }
                })


            });

            $(".cancelfromchangemodify").click(function () {
                $(".tipfromchangemodify").fadeOut(100);
            });


            //删除用户
            $(".clickdel").click(function (del) {
                var count = $("input:checked").length;
                if (count < 1) {
                    alert("至少选择一项进行删除！");
                }
                else if (count > 1) {
                    alert("只能选择一项进行修改！");
                }
                else {
                    $(".tipdel").fadeIn(200);
                }
            });

            $(".tiptopdel a").click(function (del) {
                $(".tipdel").fadeOut(200);
            });

            $(".suredel").click(function (del) {
                $obj = $("input:checked").parents("tr");
                $.post(api.del, { id: $obj.attr("Id") }, function (data) {
                    $(".tipdel").fadeOut(100);
                    window.location.reload();
                }, 'json')
            });

            $(".canceldel").click(function (del) {
                $(".tipdel").fadeOut(100);
            });

        });
    </script>
    <script type="text/javascript">
$(document).ready(function(e) {
    $(".select1").uedSelect({
		width : 345
	});
	$(".select2").uedSelect({
		width : 167
	});
	$(".select3").uedSelect({
		width : 150
	});
});
    </script>
</head>
<body>
    <div class="place">
        <span>位置：</span>
        <ul class="placeul">
            <li><a href="#">首页</a></li>
            <li><a href="#">基本设置管理</a></li>
            <li><a href="#">阶梯水价设置</a></li>
        </ul>
    </div>
    <div class="rightinfo">
        <div class="tools">
            <ul class="toolbar">
                <li class="clickreaderfromadd"><span><img src="/images/t01a.png" /></span>添加</li>
                <li class="clickfromchangemodify"><span><img src="/images/t02.png" /></span>修改</li>
                <li class="clickdel"><span><img src="/images/t03.png" /></span>删除</li>

            </ul>

        </div>
        <table class="imgtable">
            <thead>
                <tr>
                    <th>选择</th>
                    <th>阶梯序号</th>
                    <th>用水类别</th>
                    <th>阶梯区间</th>
                    <th>阶梯价格</th>
                    <th>备注信息</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="@item.Id"  WaterTypeId="@(item.WaterTypeId)" START="@item.START" EndTo="@item.EndTo" Price="@item.Price" DESCRIPTION="@item.DESCRIPTION">
                        <td><input name="" type="checkbox" value="@(item.Id)" /></td>
                        <td>@(item.Id)</td>
                        <td height="30px;">@(item.WaterType?.TypeName)</td>
                        <td><a href="#">@(item.START)-@(item.EndTo)</a></td>
                        <td>@(item.Price)</td>
                        <td>@(item.DESCRIPTION)</td> 
                    </tr>
                }
               
            </tbody>
        </table>
        <div class="pagin">
            <div class="message">共<i class="blue">@(Model.TotalItemCount)</i>条记录，共&nbsp;<i class="blue">@(Model.TotalPageCount)&nbsp;</i>页</div>
            @Html.Pager(Model, BaseController.PagerOptions)
        </div>

        <form method="post" id="form1">

            <!--阶梯水价设置-->
            <div class="tipreaderfromadd">
                <div class="tiptopreaderfromadd"><img src="/images/t06.png" /><span>阶梯水价设置</span><a></a></div>
                <div class="tipinforeaderfromadd">
                    <div class="userinfozbreaderfromadd">
                        <dt class="userinfozbtitreaderfromadd">阶梯水价设置信息</dt>
                        <ul class="seachform">
                            @Html.Action("_WaterType", "Common", "addsellssss")
                            <li>
                                <label>阶梯起量</label>
                                <input name="START" type="text" class="scinput" />
                            </li>

                            <li>
                                <label>阶梯止量</label>
                                <input name="EndTo" type="text" class="scinput" />
                            </li>

                            <li class="qx">
                                <label>阶梯价格</label>
                                <input name="Price" type="text" class="scinput" />
                            </li>
                            <li>
                                <label>备注信息</label>
                                <input name="DESCRIPTION" type="text" class="scinput" />
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="tipbtnreaderfromadd">
                    <input name="" type="button" class="surereaderfromadd" value="添加" />
                    &nbsp;
                    <input name="" type="button" class="cancelreaderfromadd" value="取消" />
                </div>
            </div>
            <!--删除用户-->
            <div class="tipdel">
                <div class="tiptopdel"><span>提示信息</span><a></a></div>
                <div class="tipinfodel">
                    <span><img src="/images/ticon01.png" /></span>
                    <div class="tiprightdel">
                        <p>确定要删除选中的阶梯水价吗？</p>
                        <cite>如果是请点击确定按钮 ，否则请点取消。</cite>
                    </div>
                </div>
                <div class="tipbtndel">
                    <input name="" type="button" class="suredel" value="确定" />
                    &nbsp;
                    <input name="" type="button" class="canceldel" value="取消" />
                </div>
            </div>
        </form>

        <form method="post" id="form2">
            <!--阶梯水价修改-->
            <div class="tipfromchangemodify">
                <div class="tiptopfromchangemodify"><img src="/images/t06.png" /><span>阶梯水价修改</span><a></a></div>
                <div class="tipinfofromchangemodify">
                    <div class="userinfozbfromchangemodify">
                        <dt class="userinfozbtitfromchangemodify">阶梯水价信息</dt>
                        <ul class="seachform">
                            @Html.Action("_WaterType", "Common", "addsellssss111111")
                            <li>
                                <label>阶梯起量</label>
                                <input name="START" type="text" class="scinput" />
                            </li>

                            <li>
                                <label>阶梯止量</label>
                                <input name="EndTo" type="text" class="scinput" />
                            </li>

                            <li class="qx">
                                <label>阶梯价格</label>
                                <input name="Price" type="text" class="scinput" />
                            </li>
                            <li>
                                <label>备注信息</label>
                                <input name="DESCRIPTION" type="text" class="scinput" />
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="tipbtnfromchangemodify">
                    @Html.Hidden("Id", "")
                    <input name="" type="button" class="surefromchangemodify" value="确定" />
                    &nbsp;
                    <input name="" type="button" class="cancelfromchangemodify" value="取消" />
                </div>
            </div>
        </form>

            <script type="text/javascript">
                $('.tablelist tbody tr:odd').addClass('odd');
            </script>
       </body>
</html>