Kongt.Web/Controllers/LoginController.cs
using Kongt.IServices;
using Kongt.Model;
using Kongt.ServiceProvider;
using Kongt.Web.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Kongt.Web.Controllers
{

    public class LoginController : BaseController
    {
        [AllowAnonymous]
        public ActionResult Json()
        {
            var model = ServiceFactory.Create<ICustomService>().Find(1);
            var str = Newtonsoft.Json.JsonConvert.SerializeObject(model, new Newtonsoft.Json.JsonSerializerSettings
            {
                ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
            });
            return Content(str);

        }



        [AllowAnonymous]
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        [ActionName("Index")]
        [HttpPost]
        public ActionResult CheckLogin(LoginModel login, string ReturnUrl)
        {

            if (ModelState.IsValid)
            {
                var entity = ServiceFactory.Create<IManagerService>().GetManagerByUserName(login.UserName);
                if (entity == null)
                {
                    ModelState.AddModelError("UserName", "用户名不存在");
                    return View(login);
                }
                else if (entity.PASSWORD != FormsAuthentication.HashPasswordForStoringInConfigFile(login.Password, "md5"))
                {
                    ModelState.AddModelError("Password", "密码输入错误");
                    return View(login);
                }
                else
                {
                    login.UserId = entity.Id;
                    login.Roles = (string.IsNullOrEmpty(entity.Roles)) ? entity.Roles.Split(',').ToList() : null;
                    var ticket = new FormsAuthenticationTicket(2, login.UserName, DateTime.Now, DateTime.Now.AddDays(1), true, JsonConvert.SerializeObject(login));
                    var cookieValue = FormsAuthentication.Encrypt(ticket);
                    FormsAuthentication.SetAuthCookie(login.UserName, false);
                    var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, cookieValue);
                    cookie.Expires = DateTime.Now.AddMinutes(30);
                    Response.AppendCookie(cookie);
                    if (!string.IsNullOrEmpty(ReturnUrl))
                    {
                        return Redirect(ReturnUrl);
                    }
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(login);

        }



        [AllowAnonymous]
        public ActionResult LoginOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index");
        }



        [AllowAnonymous]
        public ActionResult register()
        {
            ServiceFactory.Create<IManagerService>().Create(new Model.ManagerInfo()
            {
                UserName = "admin",
                PASSWORD = FormsAuthentication.HashPasswordForStoringInConfigFile("admin888", "md5"),
                Roles = "admin",
                CreateDate = DateTime.Now
            });
            return Json(new JStat(), JsonRequestBehavior.AllowGet);
        }

    }
}

Kongt.Web/Views/Login/index.cshtml
@model Kongt.Web.Models.LoginModel
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>欢迎登录合作市水务热力有限责任公司自来水用户及收费管理系统</title>
    <link href="/css/style.css" rel="stylesheet" type="text/css" />
    <script language="JavaScript" src="/js/jquery.js"></script> 
    @Scripts.Render("~/bundles/jquery") 
    <script language="javascript">
        $(function () {
            $('.loginbox').css({ 'position': 'absolute', 'left': ($(window).width() - 638) / 2 });
            $(window).resize(function () {
                $('.loginbox').css({ 'position': 'absolute', 'left': ($(window).width() - 638) / 2 });
            })
        });
    </script>

</head>

<body style="background-color:#1c77ac; background-image:url(/images/light.png); background-repeat:no-repeat; background-position:center top; overflow:hidden;">
    <div id="mainBody">
        <div id="cloud1" class="cloud"></div>
        <div id="cloud2" class="cloud"></div>
    </div>


    <div class="logintop">
        <span>欢迎登录合作市水务热力有限责任公司自来水用户及收费管理系统</span>
        <ul>
            <li><a href="#">回首页</a></li>
            <li><a href="#">帮助</a></li>
            <li><a href="#">关于</a></li>
        </ul>
    </div>

    <div class="loginbody">

        <span class="systemlogo"></span>

        <div class="loginbox">
            @using (Html.BeginForm("Index", "Login", FormMethod.Post))
            {
                <ul>
                    <li>
                        @Html.TextBoxFor(item => item.UserName, new { @class = "loginuser", onclick = "JavaScript:this.value=''" })
                        @Html.ValidationMessageFor(item => item.UserName,null,new { style="color:red"})
                    </li>
                    <li>
                        @Html.PasswordFor(item => item.Password, new { @class = "loginpwd", onclick = "JavaScript:this.value=''" })
                        @Html.ValidationMessageFor(item => item.Password, null, new { style = "color:red" })
                    </li>
                    <li>
                        <input name="" type="submit" class="loginbtn" value="登录" /> 
                        @*<label>
                            @Html.CheckBoxFor(item => item.RememberPassword) 记住密码
                        </label>
                        <label>
                            <a href="#">忘记密码？</a>
                        </label>*@
                    </li>
                </ul>
            }

        </div>

    </div>
    <div class="loginbm">技术支持：甘肃丰蓉科技信息有限公司    </div>
</body>
</html>